float32 PackageVoltage
float32 PackageCurrent

float32 SOHP
float32 SOCP
float32 AHCnow
float32 AHCmax

float32 CurrentSensorValue1
float32 CurrentSensorValue2

float32 TemperaturePack

float32 CellTemperature1
float32 CellTemperature2
float32 CellTemperature3
float32 CellTemperature4

float32 CellTemperature5
float32 CellTemperature6
float32 CellTemperature7

float32 CellVoltage1
float32 CellVoltage2
float32 CellVoltage3
float32 CellVoltage4

float32 CellVoltage5
float32 CellVoltage6
float32 CellVoltage7

float32 CellSOC1
float32 CellSOC2
float32 CellSOC3
float32 CellSOC4

float32 CellSOC5
float32 CellSOC6
float32 CellSOC7

float32 CellSOH1
float32 CellSOH2
float32 CellSOH3
float32 CellSOH4

float32 CellSOH5
float32 CellSOH6
float32 CellSOH7
