// Auto-generated. Do not edit!

// (in-package my_action_actionlib.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MyActionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.cmdType = null;
      this.scriptName = null;
      this.startIndex = null;
    }
    else {
      if (initObj.hasOwnProperty('cmdType')) {
        this.cmdType = initObj.cmdType
      }
      else {
        this.cmdType = 0;
      }
      if (initObj.hasOwnProperty('scriptName')) {
        this.scriptName = initObj.scriptName
      }
      else {
        this.scriptName = '';
      }
      if (initObj.hasOwnProperty('startIndex')) {
        this.startIndex = initObj.startIndex
      }
      else {
        this.startIndex = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MyActionGoal
    // Serialize message field [cmdType]
    bufferOffset = _serializer.int8(obj.cmdType, buffer, bufferOffset);
    // Serialize message field [scriptName]
    bufferOffset = _serializer.string(obj.scriptName, buffer, bufferOffset);
    // Serialize message field [startIndex]
    bufferOffset = _serializer.int8(obj.startIndex, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MyActionGoal
    let len;
    let data = new MyActionGoal(null);
    // Deserialize message field [cmdType]
    data.cmdType = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [scriptName]
    data.scriptName = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [startIndex]
    data.startIndex = _deserializer.int8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.scriptName.length;
    return length + 6;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_action_actionlib/MyActionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5fa6a8bfed9b5aa472426dd0455e5689';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    int8 cmdType
    string scriptName
    int8 startIndex
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MyActionGoal(null);
    if (msg.cmdType !== undefined) {
      resolved.cmdType = msg.cmdType;
    }
    else {
      resolved.cmdType = 0
    }

    if (msg.scriptName !== undefined) {
      resolved.scriptName = msg.scriptName;
    }
    else {
      resolved.scriptName = ''
    }

    if (msg.startIndex !== undefined) {
      resolved.startIndex = msg.startIndex;
    }
    else {
      resolved.startIndex = 0
    }

    return resolved;
    }
};

module.exports = MyActionGoal;
