// Generated by gencpp from file my_action_actionlib/MyActionGoal.msg
// DO NOT EDIT!


#ifndef MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONGOAL_H
#define MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_action_actionlib
{
template <class ContainerAllocator>
struct MyActionGoal_
{
  typedef MyActionGoal_<ContainerAllocator> Type;

  MyActionGoal_()
    : cmdType(0)
    , scriptName()
    , startIndex(0)  {
    }
  MyActionGoal_(const ContainerAllocator& _alloc)
    : cmdType(0)
    , scriptName(_alloc)
    , startIndex(0)  {
  (void)_alloc;
    }



   typedef int8_t _cmdType_type;
  _cmdType_type cmdType;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _scriptName_type;
  _scriptName_type scriptName;

   typedef int8_t _startIndex_type;
  _startIndex_type startIndex;





  typedef boost::shared_ptr< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MyActionGoal_

typedef ::my_action_actionlib::MyActionGoal_<std::allocator<void> > MyActionGoal;

typedef boost::shared_ptr< ::my_action_actionlib::MyActionGoal > MyActionGoalPtr;
typedef boost::shared_ptr< ::my_action_actionlib::MyActionGoal const> MyActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_actionlib::MyActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_actionlib::MyActionGoal_<ContainerAllocator1> & lhs, const ::my_action_actionlib::MyActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.cmdType == rhs.cmdType &&
    lhs.scriptName == rhs.scriptName &&
    lhs.startIndex == rhs.startIndex;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_actionlib::MyActionGoal_<ContainerAllocator1> & lhs, const ::my_action_actionlib::MyActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_actionlib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fa6a8bfed9b5aa472426dd0455e5689";
  }

  static const char* value(const ::my_action_actionlib::MyActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fa6a8bfed9b5aa4ULL;
  static const uint64_t static_value2 = 0x72426dd0455e5689ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_actionlib/MyActionGoal";
  }

  static const char* value(const ::my_action_actionlib::MyActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"int8 cmdType\n"
"string scriptName\n"
"int8 startIndex\n"
;
  }

  static const char* value(const ::my_action_actionlib::MyActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmdType);
      stream.next(m.scriptName);
      stream.next(m.startIndex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_actionlib::MyActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_actionlib::MyActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "cmdType: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmdType);
    s << indent << "scriptName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.scriptName);
    s << indent << "startIndex: ";
    Printer<int8_t>::stream(s, indent + "  ", v.startIndex);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONGOAL_H
