// Generated by gencpp from file my_action_actionlib/MyActionResult.msg
// DO NOT EDIT!


#ifndef MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONRESULT_H
#define MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_action_actionlib
{
template <class ContainerAllocator>
struct MyActionResult_
{
  typedef MyActionResult_<ContainerAllocator> Type;

  MyActionResult_()
    : result()  {
    }
  MyActionResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::my_action_actionlib::MyActionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_actionlib::MyActionResult_<ContainerAllocator> const> ConstPtr;

}; // struct MyActionResult_

typedef ::my_action_actionlib::MyActionResult_<std::allocator<void> > MyActionResult;

typedef boost::shared_ptr< ::my_action_actionlib::MyActionResult > MyActionResultPtr;
typedef boost::shared_ptr< ::my_action_actionlib::MyActionResult const> MyActionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_actionlib::MyActionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_actionlib::MyActionResult_<ContainerAllocator1> & lhs, const ::my_action_actionlib::MyActionResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_actionlib::MyActionResult_<ContainerAllocator1> & lhs, const ::my_action_actionlib::MyActionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_actionlib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_actionlib::MyActionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_actionlib::MyActionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_actionlib::MyActionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::my_action_actionlib::MyActionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_actionlib/MyActionResult";
  }

  static const char* value(const ::my_action_actionlib::MyActionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"string result\n"
;
  }

  static const char* value(const ::my_action_actionlib::MyActionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyActionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_actionlib::MyActionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_actionlib::MyActionResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONRESULT_H
