// Generated by gencpp from file my_action_actionlib/MyActionFeedback.msg
// DO NOT EDIT!


#ifndef MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONFEEDBACK_H
#define MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_action_actionlib
{
template <class ContainerAllocator>
struct MyActionFeedback_
{
  typedef MyActionFeedback_<ContainerAllocator> Type;

  MyActionFeedback_()
    : action()
    , currentIndex(0)  {
    }
  MyActionFeedback_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , currentIndex(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef int8_t _currentIndex_type;
  _currentIndex_type currentIndex;





  typedef boost::shared_ptr< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MyActionFeedback_

typedef ::my_action_actionlib::MyActionFeedback_<std::allocator<void> > MyActionFeedback;

typedef boost::shared_ptr< ::my_action_actionlib::MyActionFeedback > MyActionFeedbackPtr;
typedef boost::shared_ptr< ::my_action_actionlib::MyActionFeedback const> MyActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator1> & lhs, const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.currentIndex == rhs.currentIndex;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator1> & lhs, const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_actionlib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71787da51c21b713ad07f51cd9d1e7eb";
  }

  static const char* value(const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71787da51c21b713ULL;
  static const uint64_t static_value2 = 0xad07f51cd9d1e7ebULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_actionlib/MyActionFeedback";
  }

  static const char* value(const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"string action\n"
"int8 currentIndex\n"
"\n"
"\n"
;
  }

  static const char* value(const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.currentIndex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_actionlib::MyActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_actionlib::MyActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "currentIndex: ";
    Printer<int8_t>::stream(s, indent + "  ", v.currentIndex);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_ACTIONLIB_MESSAGE_MYACTIONFEEDBACK_H
