// Generated by gencpp from file teco_msgs/battery_srv.msg
// DO NOT EDIT!


#ifndef TECO_MSGS_MESSAGE_BATTERY_SRV_H
#define TECO_MSGS_MESSAGE_BATTERY_SRV_H

#include <ros/service_traits.h>


#include <teco_msgs/battery_srvRequest.h>
#include <teco_msgs/battery_srvResponse.h>


namespace teco_msgs
{

struct battery_srv
{

typedef battery_srvRequest Request;
typedef battery_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct battery_srv
} // namespace teco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::teco_msgs::battery_srv > {
  static const char* value()
  {
    return "c8b59f64747d119147a5ffdefffd3858";
  }

  static const char* value(const ::teco_msgs::battery_srv&) { return value(); }
};

template<>
struct DataType< ::teco_msgs::battery_srv > {
  static const char* value()
  {
    return "teco_msgs/battery_srv";
  }

  static const char* value(const ::teco_msgs::battery_srv&) { return value(); }
};


// service_traits::MD5Sum< ::teco_msgs::battery_srvRequest> should match
// service_traits::MD5Sum< ::teco_msgs::battery_srv >
template<>
struct MD5Sum< ::teco_msgs::battery_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::teco_msgs::battery_srv >::value();
  }
  static const char* value(const ::teco_msgs::battery_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::teco_msgs::battery_srvRequest> should match
// service_traits::DataType< ::teco_msgs::battery_srv >
template<>
struct DataType< ::teco_msgs::battery_srvRequest>
{
  static const char* value()
  {
    return DataType< ::teco_msgs::battery_srv >::value();
  }
  static const char* value(const ::teco_msgs::battery_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::teco_msgs::battery_srvResponse> should match
// service_traits::MD5Sum< ::teco_msgs::battery_srv >
template<>
struct MD5Sum< ::teco_msgs::battery_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::teco_msgs::battery_srv >::value();
  }
  static const char* value(const ::teco_msgs::battery_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::teco_msgs::battery_srvResponse> should match
// service_traits::DataType< ::teco_msgs::battery_srv >
template<>
struct DataType< ::teco_msgs::battery_srvResponse>
{
  static const char* value()
  {
    return DataType< ::teco_msgs::battery_srv >::value();
  }
  static const char* value(const ::teco_msgs::battery_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TECO_MSGS_MESSAGE_BATTERY_SRV_H
