// Generated by gencpp from file teco_msgs/battery_srvRequest.msg
// DO NOT EDIT!


#ifndef TECO_MSGS_MESSAGE_BATTERY_SRVREQUEST_H
#define TECO_MSGS_MESSAGE_BATTERY_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace teco_msgs
{
template <class ContainerAllocator>
struct battery_srvRequest_
{
  typedef battery_srvRequest_<ContainerAllocator> Type;

  battery_srvRequest_()
    : input()  {
    }
  battery_srvRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::teco_msgs::battery_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teco_msgs::battery_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct battery_srvRequest_

typedef ::teco_msgs::battery_srvRequest_<std::allocator<void> > battery_srvRequest;

typedef boost::shared_ptr< ::teco_msgs::battery_srvRequest > battery_srvRequestPtr;
typedef boost::shared_ptr< ::teco_msgs::battery_srvRequest const> battery_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teco_msgs::battery_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teco_msgs::battery_srvRequest_<ContainerAllocator1> & lhs, const ::teco_msgs::battery_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teco_msgs::battery_srvRequest_<ContainerAllocator1> & lhs, const ::teco_msgs::battery_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teco_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teco_msgs::battery_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teco_msgs::battery_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teco_msgs::battery_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39e92f1778057359c64c7b8a7d7b19de";
  }

  static const char* value(const ::teco_msgs::battery_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39e92f1778057359ULL;
  static const uint64_t static_value2 = 0xc64c7b8a7d7b19deULL;
};

template<class ContainerAllocator>
struct DataType< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teco_msgs/battery_srvRequest";
  }

  static const char* value(const ::teco_msgs::battery_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input\n"
;
  }

  static const char* value(const ::teco_msgs::battery_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct battery_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teco_msgs::battery_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teco_msgs::battery_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TECO_MSGS_MESSAGE_BATTERY_SRVREQUEST_H
