(cl:defpackage my_action_actionlib-msg
  (:use )
  (:export
   "<MYACTIONACTION>"
   "MYACTIONACTION"
   "<MYACTIONACTIONFEEDBACK>"
   "MYACTIONACTIONFEEDBACK"
   "<MYACTIONACTIONGOAL>"
   "MYACTIONACTIONGOAL"
   "<MYACTIONACTIONRESULT>"
   "MYACTIONACTIONRESULT"
   "<MYACTIONFEEDBACK>"
   "MYACTIONFEEDBACK"
   "<MYACTIONGOAL>"
   "MYACTIONGOAL"
   "<MYACTIONRESULT>"
   "MYACTIONRESULT"
   "<ACTIONCMD>"
   "ACTIONCMD"
   "<FEEDBACKMSG>"
   "FEEDBACKMSG"
  ))

