; Auto-generated. Do not edit!


(cl:in-package my_action_actionlib-msg)


;//! \htmlinclude MyActionGoal.msg.html

(cl:defclass <MyActionGoal> (roslisp-msg-protocol:ros-message)
  ((cmdType
    :reader cmdType
    :initarg :cmdType
    :type cl:fixnum
    :initform 0)
   (scriptName
    :reader scriptName
    :initarg :scriptName
    :type cl:string
    :initform "")
   (startIndex
    :reader startIndex
    :initarg :startIndex
    :type cl:fixnum
    :initform 0))
)

(cl:defclass MyActionGoal (<MyActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MyActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MyActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_actionlib-msg:<MyActionGoal> is deprecated: use my_action_actionlib-msg:MyActionGoal instead.")))

(cl:ensure-generic-function 'cmdType-val :lambda-list '(m))
(cl:defmethod cmdType-val ((m <MyActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_actionlib-msg:cmdType-val is deprecated.  Use my_action_actionlib-msg:cmdType instead.")
  (cmdType m))

(cl:ensure-generic-function 'scriptName-val :lambda-list '(m))
(cl:defmethod scriptName-val ((m <MyActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_actionlib-msg:scriptName-val is deprecated.  Use my_action_actionlib-msg:scriptName instead.")
  (scriptName m))

(cl:ensure-generic-function 'startIndex-val :lambda-list '(m))
(cl:defmethod startIndex-val ((m <MyActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_actionlib-msg:startIndex-val is deprecated.  Use my_action_actionlib-msg:startIndex instead.")
  (startIndex m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MyActionGoal>) ostream)
  "Serializes a message object of type '<MyActionGoal>"
  (cl:let* ((signed (cl:slot-value msg 'cmdType)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'scriptName))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'scriptName))
  (cl:let* ((signed (cl:slot-value msg 'startIndex)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MyActionGoal>) istream)
  "Deserializes a message object of type '<MyActionGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'cmdType) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'scriptName) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'scriptName) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'startIndex) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MyActionGoal>)))
  "Returns string type for a message object of type '<MyActionGoal>"
  "my_action_actionlib/MyActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MyActionGoal)))
  "Returns string type for a message object of type 'MyActionGoal"
  "my_action_actionlib/MyActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MyActionGoal>)))
  "Returns md5sum for a message object of type '<MyActionGoal>"
  "5fa6a8bfed9b5aa472426dd0455e5689")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MyActionGoal)))
  "Returns md5sum for a message object of type 'MyActionGoal"
  "5fa6a8bfed9b5aa472426dd0455e5689")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MyActionGoal>)))
  "Returns full string definition for message of type '<MyActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int8 cmdType~%string scriptName~%int8 startIndex~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MyActionGoal)))
  "Returns full string definition for message of type 'MyActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int8 cmdType~%string scriptName~%int8 startIndex~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MyActionGoal>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'scriptName))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MyActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MyActionGoal
    (cl:cons ':cmdType (cmdType msg))
    (cl:cons ':scriptName (scriptName msg))
    (cl:cons ':startIndex (startIndex msg))
))
