// Generated by gencpp from file my_dynparam_service/get_dynparam_serviceResponse.msg
// DO NOT EDIT!


#ifndef MY_DYNPARAM_SERVICE_MESSAGE_GET_DYNPARAM_SERVICERESPONSE_H
#define MY_DYNPARAM_SERVICE_MESSAGE_GET_DYNPARAM_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_dynparam_service
{
template <class ContainerAllocator>
struct get_dynparam_serviceResponse_
{
  typedef get_dynparam_serviceResponse_<ContainerAllocator> Type;

  get_dynparam_serviceResponse_()
    : output()  {
    }
  get_dynparam_serviceResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_dynparam_serviceResponse_

typedef ::my_dynparam_service::get_dynparam_serviceResponse_<std::allocator<void> > get_dynparam_serviceResponse;

typedef boost::shared_ptr< ::my_dynparam_service::get_dynparam_serviceResponse > get_dynparam_serviceResponsePtr;
typedef boost::shared_ptr< ::my_dynparam_service::get_dynparam_serviceResponse const> get_dynparam_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator1> & lhs, const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator1> & lhs, const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_dynparam_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_dynparam_service/get_dynparam_serviceResponse";
  }

  static const char* value(const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output\n"
"\n"
;
  }

  static const char* value(const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_dynparam_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_dynparam_service::get_dynparam_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DYNPARAM_SERVICE_MESSAGE_GET_DYNPARAM_SERVICERESPONSE_H
