// Generated by gencpp from file my_dynparam_service/set_dynparam_service.msg
// DO NOT EDIT!


#ifndef MY_DYNPARAM_SERVICE_MESSAGE_SET_DYNPARAM_SERVICE_H
#define MY_DYNPARAM_SERVICE_MESSAGE_SET_DYNPARAM_SERVICE_H

#include <ros/service_traits.h>


#include <my_dynparam_service/set_dynparam_serviceRequest.h>
#include <my_dynparam_service/set_dynparam_serviceResponse.h>


namespace my_dynparam_service
{

struct set_dynparam_service
{

typedef set_dynparam_serviceRequest Request;
typedef set_dynparam_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_dynparam_service
} // namespace my_dynparam_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_dynparam_service::set_dynparam_service > {
  static const char* value()
  {
    return "c63e85f503b805d84df783e71c6bb0d2";
  }

  static const char* value(const ::my_dynparam_service::set_dynparam_service&) { return value(); }
};

template<>
struct DataType< ::my_dynparam_service::set_dynparam_service > {
  static const char* value()
  {
    return "my_dynparam_service/set_dynparam_service";
  }

  static const char* value(const ::my_dynparam_service::set_dynparam_service&) { return value(); }
};


// service_traits::MD5Sum< ::my_dynparam_service::set_dynparam_serviceRequest> should match
// service_traits::MD5Sum< ::my_dynparam_service::set_dynparam_service >
template<>
struct MD5Sum< ::my_dynparam_service::set_dynparam_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_dynparam_service::set_dynparam_service >::value();
  }
  static const char* value(const ::my_dynparam_service::set_dynparam_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_dynparam_service::set_dynparam_serviceRequest> should match
// service_traits::DataType< ::my_dynparam_service::set_dynparam_service >
template<>
struct DataType< ::my_dynparam_service::set_dynparam_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::my_dynparam_service::set_dynparam_service >::value();
  }
  static const char* value(const ::my_dynparam_service::set_dynparam_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_dynparam_service::set_dynparam_serviceResponse> should match
// service_traits::MD5Sum< ::my_dynparam_service::set_dynparam_service >
template<>
struct MD5Sum< ::my_dynparam_service::set_dynparam_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_dynparam_service::set_dynparam_service >::value();
  }
  static const char* value(const ::my_dynparam_service::set_dynparam_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_dynparam_service::set_dynparam_serviceResponse> should match
// service_traits::DataType< ::my_dynparam_service::set_dynparam_service >
template<>
struct DataType< ::my_dynparam_service::set_dynparam_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::my_dynparam_service::set_dynparam_service >::value();
  }
  static const char* value(const ::my_dynparam_service::set_dynparam_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_DYNPARAM_SERVICE_MESSAGE_SET_DYNPARAM_SERVICE_H
