(cl:defpackage my_dynparam_service-srv
  (:use )
  (:export
   "GET_DYNPARAM_SERVICE"
   "<GET_DYNPARAM_SERVICE-REQUEST>"
   "GET_DYNPARAM_SERVICE-REQUEST"
   "<GET_DYNPARAM_SERVICE-RESPONSE>"
   "GET_DYNPARAM_SERVICE-RESPONSE"
   "SET_DYNPARAM_SERVICE"
   "<SET_DYNPARAM_SERVICE-REQUEST>"
   "SET_DYNPARAM_SERVICE-REQUEST"
   "<SET_DYNPARAM_SERVICE-RESPONSE>"
   "SET_DYNPARAM_SERVICE-RESPONSE"
  ))

